apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: ai
    version: mbappe
  name: ai-mbappe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
      version: mbappe
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        project: mesh-arena
        app: ai
        version: mbappe
        vm: hotspot
    spec:
      containers:
      - image: jotak/demo-mesh-arena-ai:1.1.7
        imagePullPolicy: IfNotPresent
        name: ai-locals
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: AB_OFF
          value: "1"
        - name: JAVA_OPTIONS
          value: "-Dvertx.disableDnsResolver=true"
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: locals
        - name: PLAYER_NAME
          value: "MbappÃ©"
        - name: PLAYER_SPEED
          value: 95
        - name: PLAYER_ACCURACY
          value: 0.89
        - name: PLAYER_SKILL
          value: 11
        - name: PLAYER_SHOOT
          value: 300
        - name: PLAYER_ATTACKING
          value: 90
        - name: PLAYER_ATT_SHOOT_FAST
          value: 20
        - name: PLAYER_DEF_SHOOT_FAST
          value: 40
        - name: PLAYER_COLOR
          value: cyan
        - name: JAEGER_SERVICE_NAME
          value: ai.default
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://tracing.istio-system.svc/api/traces>
        securityContext:
          privileged: false
