apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ai-visitors
    version: goat
  name: ai-visitors-goat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-visitors
      version: goat
  template:
    metadata:
      labels:
        app: ai-visitors
        version: goat
    spec:
      containers:
      - image: jotak/demo-mesh-arena-ai:latest
        imagePullPolicy: IfNotPresent
        name: ai-visitors
        env:
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: visitors
        - name: PLAYER_COLOR
          value: yellow
        - name: PLAYER_NAME
          value: une ch√®vre jaune
        securityContext:
          privileged: false
