apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: ai
    version: visitors
  name: ai-visitors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai
      version: visitors
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        project: mesh-arena
        app: ai
        version: visitors
        vm: openj9
    spec:
      containers:
      - image: jotak/demo-mesh-arena-oj9-ai:1.1.7
        imagePullPolicy: IfNotPresent
        name: ai-visitors-oj9
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: AB_OFF
          value: "1"
        - name: JAVA_OPTIONS
          value: "-Dvertx.disableDnsResolver=true"
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: visitors
        - name: PLAYER_COLOR
          value: yellow
        - name: PLAYER_NAME
          value: yellow goat
        - name: JAEGER_SERVICE_NAME
          value: ai-visitors
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system.svc:14268/api/traces
        securityContext:
          privileged: false
