apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ai-locals
    version: mbappe
  name: ai-locals-mbappe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-locals
      version: mbappe
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "9090"
        kiali.io/runtimes: vertx-client,vertx-pool
      labels:
        app: ai-locals
        version: mbappe
    spec:
      containers:
      - image: jotak/demo-mesh-arena-ai:1.1.2
        imagePullPolicy: IfNotPresent
        name: ai-locals
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: AB_OFF
          value: "1"
        - name: JAVA_OPTIONS
          value: "-Dvertx.disableDnsResolver=true"
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: locals
        - name: PLAYER_NAME
          value: "Mbapp√©"
        - name: PLAYER_SPEED
          value: 95
        - name: PLAYER_ACCURACY
          value: 0.89
        - name: PLAYER_SKILL
          value: 11
        - name: PLAYER_SHOOT
          value: 300
        - name: PLAYER_ATTACKING
          value: 90
        - name: PLAYER_ATT_SHOOT_FAST
          value: 20
        - name: PLAYER_DEF_SHOOT_FAST
          value: 40
        - name: PLAYER_COLOR
          value: cyan
        - name: JAEGER_SERVICE_NAME
          value: ai-locals
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: 1
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system.svc:14268/api/traces
        securityContext:
          privileged: false
